.TH "H_muscle.Hill_type_muscle" 3 "Thu May 7 2020" "Hill-type muscle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
H_muscle.Hill_type_muscle
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, F_0=3549, l_0=0\&.05, l_t=0\&.25, phi_0=0\&.2, A=\-0\&.1)"
.br
.ti -1c
.RI "def \fBcal_muscle_activation\fP (self, u)"
.br
.ti -1c
.RI "def \fBcal_muscle_fiber_length\fP (self, l_mt)"
.br
.ti -1c
.RI "def \fBcal_normalized_muscle_fiber_length\fP (self, l_mt)"
.br
.ti -1c
.RI "def \fBget_active_force_length_function\fP (self)"
.br
.ti -1c
.RI "def \fBget_passive_force_length_function\fP (self)"
.br
.ti -1c
.RI "def \fBget_active_force_length_value\fP (self, l_mt)"
.br
.ti -1c
.RI "def \fBget_passive_force_length_value\fP (self, l_mt)"
.br
.ti -1c
.RI "def \fBmes_active_muscle_force_value\fP (self, l_mt)"
.br
.ti -1c
.RI "def \fBmes_passive_muscle_force_value\fP (self, l_mt)"
.br
.ti -1c
.RI "def \fBcal_active_muscle_force\fP (self, l_mt, u)"
.br
.ti -1c
.RI "def \fBcal_passive_muscle_force\fP (self, l_mt)"
.br
.ti -1c
.RI "def \fBcal_muscle_fiber_force\fP (self, l_mt, u)"
.br
.ti -1c
.RI "def \fBplot_force\fP (self, u, active_force, total_force, title)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBF_0\fP"
.br
.ti -1c
.RI "\fBl_0\fP"
.br
.ti -1c
.RI "\fBl_t\fP"
.br
.ti -1c
.RI "\fBphi_0\fP"
.br
.ti -1c
.RI "\fBA\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Some properties are considered constant in this model:
        Muscle maximal isometric force = 3549 N
        Muscle optimal fibre length = 0.05m
        Tendon infinitely stiff with a constant length = 0.25m
        Pennation angle = 0.20 rad
        Shape factor A = -0.1

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def H_muscle\&.Hill_type_muscle\&.cal_active_muscle_force ( self,  l_mt,  u)"

.PP
.nf
This method returns the active muscle force generated by the contractile element
    Input: Total muscle-tendon length (l_mt), muscle excitation value (u)
    Output: Active muscle force (F_A)
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.cal_muscle_activation ( self,  u)"

.PP
.nf
This method returns the muscle activation from muscle excitation profile
    Input: Muscle excitation value (u)
    Output: Muscle activation value (a)
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.cal_muscle_fiber_force ( self,  l_mt,  u)"

.PP
.nf
This method returns the total muscle force
    Input: Total muscle-tendon length (l_mt), muscle excitation value (u)
    Output: total muscle fiber force (F)
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.cal_muscle_fiber_length ( self,  l_mt)"

.PP
.nf
This method returns the muscle fiber length from the total muscle-tendon length
    Input: Total muscle-tendon length (l_mt)
    Output: Muscle fiber length (l_m)
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.cal_normalized_muscle_fiber_length ( self,  l_mt)"

.PP
.nf
This method returns the normalised muscle fiber length from the total muscle-tendon length
    Input: Total muscle-tendon length (l_mt)
    Output: Normalised Muscle fiber length (l_hat)
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.cal_passive_muscle_force ( self,  l_mt)"

.PP
.nf
This method returns the passive muscle force generated by the passive element
    Input: Total muscle-tendon length (l_mt)
    Output: Passive muscle force (F_P)
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.get_active_force_length_function ( self)"

.PP
.nf
This method returns the active force-length curve
    Input: None
    Output: Active force-length function (f_a)
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.get_active_force_length_value ( self,  l_mt)"

.PP
.nf
This method returns the active force-length value corresponding to the specific value of muscle fiber length
    Input: Total muscle-tendon length (l_mt)
    Output: Active force-length value (f_am)
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.get_passive_force_length_function ( self)"

.PP
.nf
This method returns the passive force-length curve
    Input: None
    Output: Passive force-length function (f_p)
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.get_passive_force_length_value ( self,  l_mt)"

.PP
.nf
This method returns the passive force-length value corresponding to the specific value of muscle fiber length
    Input: Total muscle-tendon length (l_mt)
    Output: Passive force-length value (f_pm)
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.mes_active_muscle_force_value ( self,  l_mt)"

.PP
.nf
This method prints a message showing the active force-length value corresponding to the value of l_mt
    Input: Total muscle-tendon length (l_mt)
    Output: A string
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.mes_passive_muscle_force_value ( self,  l_mt)"

.PP
.nf
This method prints a message showing the passive force-length value corresponding to the value of l_mt
    Input: Total muscle-tendon length (l_mt)
    Output: A string
.fi
.PP
 
.SS "def H_muscle\&.Hill_type_muscle\&.plot_force ( self,  u,  active_force,  total_force,  title)"

.PP
.nf
This method plots the calculated active muscle force and total muscle force over a range of muscle excitations
    Input: muscle excitation value (u), active muscle force (F_A), total muscle force (F), title of the graph
    Output: a line graph
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hill-type muscle from the source code\&.
