.TH "H_muscle" 3 "Thu May 7 2020" "Hill-type muscle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
H_muscle
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHill_type_muscle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
@package docstring
This program is made by Minh Truong.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hill-type muscle from the source code\&.
