.TH "md__r_e_a_d_m_e" 3 "Thu May 7 2020" "Hill-type muscle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Hill-type-Muscle-model 
This is a programming assignment for the assessment of a PhD position\&. The task is to compute muscle-tendon force using the Hill-type muscle model with three different total muscle-tendon lengths\&. 
